<template><div><h1 id="json-reports" tabindex="-1"><a class="header-anchor" href="#json-reports" aria-hidden="true">#</a> JSON reports</h1>
<p>JSON reports can be enabled using the <code v-pre>json.enabled</code> property. The preprocessor uses <a href="https://github.com/davidtheclark/cosmiconfig" target="_blank" rel="noopener noreferrer">cosmiconfig<ExternalLinkIcon/></a>, which means you can place configuration options in EG. <code v-pre>.cypress-cucumber-preprocessorrc.json</code> or <code v-pre>package.json</code>. An example configuration is shown below.</p>
<div class="language-json ext-json line-numbers-mode"><pre v-pre class="language-json"><code><span class="token punctuation">{</span>
  <span class="token property">"json"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token property">"enabled"</span><span class="token operator">:</span> <span class="token boolean">true</span>
  <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>This <strong>requires</strong> you to have registered this module in your <a href="https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Plugins-file" target="_blank" rel="noopener noreferrer">plugin file<ExternalLinkIcon/></a>, as shown below.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> addCucumberPreprocessorPlugin <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@badeball/cypress-cucumber-preprocessor"</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token keyword">async</span> <span class="token punctuation">(</span>
  on<span class="token operator">:</span> Cypress<span class="token punctuation">.</span>PluginEvents<span class="token punctuation">,</span>
  config<span class="token operator">:</span> Cypress<span class="token punctuation">.</span>PluginConfigOptions
<span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">Promise</span><span class="token operator">&lt;</span>Cypress<span class="token punctuation">.</span>PluginConfigOptions<span class="token operator">></span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">await</span> <span class="token function">addCucumberPreprocessorPlugin</span><span class="token punctuation">(</span>on<span class="token punctuation">,</span> config<span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">// Make sure to return the config object as it might have been modified by the plugin.</span>
  <span class="token keyword">return</span> config<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>This also <strong>requires</strong> you to have downloaded and installed the <a href="https://github.com/cucumber/json-formatter" target="_blank" rel="noopener noreferrer">cucumber-json-formatter<ExternalLinkIcon/></a> <strong>yourself</strong>. Arch Linux users can install it from <a href="https://aur.archlinux.org/packages/cucumber-json-formatter" target="_blank" rel="noopener noreferrer">AUR<ExternalLinkIcon/></a>.</p>
<p>The location of the executable is configurable through the <code v-pre>json.formatter</code> property, but it will by default search for <code v-pre>cucumber-json-formatter</code> in your <code v-pre>PATH</code>.</p>
<p>The report is outputted to <code v-pre>cucumber-report.json</code> in the project directory, but can be configured through the <code v-pre>json.output</code> property.</p>
<h2 id="screenshots" tabindex="-1"><a class="header-anchor" href="#screenshots" aria-hidden="true">#</a> Screenshots</h2>
<p>Screenshots are automatically added to JSON reports, including that of failed tests (unless you have disabled <code v-pre>screenshotOnRunFailure</code>).</p>
<h2 id="attachments" tabindex="-1"><a class="header-anchor" href="#attachments" aria-hidden="true">#</a> Attachments</h2>
<p>Text, images and other data can be added to the output of the messages and JSON reports with attachments.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> Given<span class="token punctuation">,</span> attach <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@badeball/cypress-cucumber-preprocessor"</span><span class="token punctuation">;</span>

<span class="token function">Given</span><span class="token punctuation">(</span><span class="token string">"a step"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token function">attach</span><span class="token punctuation">(</span><span class="token string">"foobar"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>By default, text is saved with a MIME type of text/plain. You can also specify a different MIME type.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> Given<span class="token punctuation">,</span> attach <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@badeball/cypress-cucumber-preprocessor"</span><span class="token punctuation">;</span>

<span class="token function">Given</span><span class="token punctuation">(</span><span class="token string">"a step"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token function">attach</span><span class="token punctuation">(</span><span class="token string">'{ "name": "foobar" }'</span><span class="token punctuation">,</span> <span class="token string">"application/json"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Images and other binary data can be attached using a ArrayBuffer. The data will be base64 encoded in the output.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> Given<span class="token punctuation">,</span> attach <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@badeball/cypress-cucumber-preprocessor"</span><span class="token punctuation">;</span>

<span class="token function">Given</span><span class="token punctuation">(</span><span class="token string">"a step"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token function">attach</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">TextEncoder</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">encode</span><span class="token punctuation">(</span><span class="token string">"foobar"</span><span class="token punctuation">)</span><span class="token punctuation">.</span>buffer<span class="token punctuation">,</span> <span class="token string">"text/plain"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>If you've already got a base64-encoded string, you can prefix your mime type with <code v-pre>base64:</code> to indicate this.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> Given<span class="token punctuation">,</span> attach <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"@badeball/cypress-cucumber-preprocessor"</span><span class="token punctuation">;</span>

<span class="token function">Given</span><span class="token punctuation">(</span><span class="token string">"a step"</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token function">attach</span><span class="token punctuation">(</span><span class="token string">"Zm9vYmFy"</span><span class="token punctuation">,</span> <span class="token string">"base64:text/plain"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>
